{{- if .Values.metrics.enabled}}
apiVersion: v1
kind: Service
metadata:
  name: "{{ template "harbor.exporter" . }}"
  labels:
{{ include "harbor.labels" . | indent 4 }}
spec:
  ports:
    - name: {{ ternary "https-metrics" "http-metrics" .Values.internalTLS.enabled }}
      port: {{ .Values.metrics.exporter.port }}
  selector:
{{ include "harbor.matchLabels" . | indent 4 }}
    component: exporter
{{ end }}
